# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15b144877b25496844b53c25ce4abab4daf32c37ad9317de6438ef4ebc6dd1a1ccdb1a4613da6f4121c3d1eed72d5192fe170a2b449b2960d642917cf85c6ab2

test:
  secret_key_base: becafe5eb1fae343e9fa57fc04f48aa067badfd9b5403de684a28a869a709b073a170c6c7e0d9c939b9865ed7ce2a525c3ffcd23768217c7f1325a0c7632cb17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
